### ISSUE TITLE
 panicked at 'called `Result::unwrap()` on an `Err` value: MessageFormatError'

### ISSUE THREAD

**Issue by mappedbyte** [berick/sip2-client-rs#1]
Hello, rustacean, when I use Sip2 library and login method, the returned result is abnormal

**Comment by mappedbyte** [comment]
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src/result.rs:1078:23

**Comment by berick** [comment]
Hi, more details would be helpful.  How are you invoking the login method?  What params, etc?

**Comment by mappedbyte** [comment]
> Hi, more details would be helpful. How are you invoking the login method? What params, etc?

Thank you very much for your reply. Please wait a moment

**Comment by mappedbyte** [comment]
I used it according to the instructions, but when I received the returned message, there was an exception: SIP message format error

**Comment by mappedbyte** [comment]
When I use the packet capturing tool, the returned information is as follows 
[https://youdaooss.oss-cn-shanghai.aliyuncs.com/ware.jpg](url)

**Comment by berick** [comment]
Thanks for the info.  I tried to recreate the issue based on your image, but the message still parsed OK.  Example:

```
    let s = "94 12022073140 806A0|AF|AG|AY 1AZEBBA";
    let m = Message::from_sip(s).unwrap();
    println!("MESSAGE: {}", m);
    return;
```

Prints:

```
MESSAGE: 94 Login Response
   ok.................................
12 unknown............................022073140 806A0
AY sequence number.................... 1AZEBBA
```

If you could create a chunk of code like the above that produces the error, that would be very helpful.

**Comment by mappedbyte** [comment]
> 谢谢（你的）信息。我尝试根据您的图像重新创建问题，但消息仍然可以解析。例子：
> 
> ```
>     let s = "94 12022073140 806A0|AF|AG|AY 1AZEBBA";
>     let m = Message::from_sip(s).unwrap();
>     println!("MESSAGE: {}", m);
>     return;
> ```
> 
> 印刷：
> 
> ```
> MESSAGE: 94 Login Response
>    ok.................................
> 12 unknown............................022073140 806A0
> AY sequence number.................... 1AZEBBA
> ```
> 
> 如果您可以创建像上面那样产生错误的代码块，那将非常有帮助。

`   

    let mut req = Message::new(
        &spec::M_LOGIN,
        vec![
            FixedField::new(&spec::FF_UID_ALGO, "0").unwrap(),
            FixedField::new(&spec::FF_PWD_ALGO, "0").unwrap(),
        ],
        vec![
            Field::new(spec::F_LOGIN_UID.code, user),
            Field::new(spec::F_LOGIN_PWD.code, pass),
        ]
    );
    req.maybe_add_field(spec::F_LOCATION_CODE.code, Option::Some(cp));

    let resp = con.sendrecv(&req);
    match resp {
        Ok(msg) => println!("{}", msg),
        Err(E)=>println!("error:{}",E)
    }`

**Comment by mappedbyte** [comment]
> 谢谢（你的）信息。我尝试根据您的图像重新创建问题，但消息仍然可以解析。例子：
> 
> ```
>     let s = "94 12022073140 806A0|AF|AG|AY 1AZEBBA";
>     let m = Message::from_sip(s).unwrap();
>     println!("MESSAGE: {}", m);
>     return;
> ```
> 
> 印刷：
> 
> ```
> MESSAGE: 94 Login Response
>    ok.................................
> 12 unknown............................022073140 806A0
> AY sequence number.................... 1AZEBBA
> ```
> 
> 如果您可以创建像上面那样产生错误的代码块，那将非常有帮助。

I use it like this and return error: SIP message format error. I don't know where the problem is

**Comment by mappedbyte** [comment]
![image](https://user-images.githubusercontent.com/45536185/182055901-5c9313ab-33ba-4d5b-a7a6-f5c23f6e051f.png)

**Comment by mappedbyte** [comment]
Thank you for your reply again. I found the problem in this location by using debug, which is located in the recv method inside the sendrecv method

**Comment by berick** [comment]
Hi, it would be most helpful if you could provide a code sample I could run that produces the error.  I need to know what data specifically is causing it to break.

**Comment by mappedbyte** [comment]
> 嗨，如果您能提供一个我可以运行并产生错误的代码示例，那将是最有帮助的。我需要知道具体是什么数据导致它中断。

Thank you for your reply. I have posted the above code. I have provided the hexadecimal data and picture data of the returned message earlier. I found that some of them were converted into ASCII, and others could not be recognized by utf8 format, because it exceeded the standard ascii 128

**Comment by mappedbyte** [comment]
Hello, I have found the reason. The returned data format is GBK, and the code uses UTF-8 encoding format. When I use java socket, I receive garbled code, and do not report an error and exit like rust. Therefore, I guess it is a coding problem. When I use GBK coding, everything is normal, but I do not know how to use GBK coding in the Sip2 client RS library

**Comment by berick** [comment]
I believe you're right.  Presumably using UTF-16 would resolve this, but that requires the SIP client and server to agree up front to communicate in UTF-16.  I could potentially add a command line option to enable UTF-16 support in the Rust SIP2 library, but that will require some investigation/coding.  No promises at this point.  Patches welcome, of course.

**Comment by mappedbyte** [comment]
> 

I think it would be better if you could add custom codec options

**Comment by mappedbyte** [comment]
Thank you very much for helping me solve the problem
